apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kenyan-ride-share-backend
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        # CPU allocation
        run.googleapis.com/cpu-throttling: "false"
        # Memory allocation
        run.googleapis.com/memory: "512Mi"
        # CPU allocation
        run.googleapis.com/cpu: "1"
        # Maximum number of instances
        run.googleapis.com/max-instances: "10"
        # Minimum number of instances
        run.googleapis.com/min-instances: "0"
        # Concurrency
        run.googleapis.com/execution-environment: gen2
        # Timeout
        run.googleapis.com/timeout: "300s"
        # VPC Connector (if needed for database connectivity)
        # run.googleapis.com/vpc-access-connector: projects/PROJECT_ID/locations/us-central1/connectors/kenyan-ride-share-connector
        # run.googleapis.com/vpc-access-egress: private-ranges-only
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - image: us-central1-docker.pkg.dev/PROJECT_ID/kenyan-ride-share-backend/kenyan-ride-share-backend:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: PORT
          value: "8080"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: DATABASE_URL
              key: latest
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: JWT_SECRET
              key: latest
        - name: MPESA_CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              name: MPESA_CONSUMER_KEY
              key: latest
        - name: MPESA_CONSUMER_SECRET
          valueFrom:
            secretKeyRef:
              name: MPESA_CONSUMER_SECRET
              key: latest
        - name: MPESA_PASSKEY
          valueFrom:
            secretKeyRef:
              name: MPESA_PASSKEY
              key: latest
        - name: MPESA_SHORTCODE
          valueFrom:
            secretKeyRef:
              name: MPESA_SHORTCODE
              key: latest
        - name: MPESA_CALLBACK_URL
          valueFrom:
            secretKeyRef:
              name: MPESA_CALLBACK_URL
              key: latest
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
  traffic:
  - percent: 100
    latestRevision: true
